import { MenuItem } from "@/types";

/**
 * MedChina navigation. Clinical work comes first (home → patients), the AI
 * assistant next, then the superadmin console. The template's UI showcase is
 * kept as a development reference and should be pruned before launch.
 */
export const leftMenuItems: MenuItem[] = [
  {
    id: "inicio",
    icon: "NiHome",
    label: "menu-inicio",
    description: "menu-inicio-description",
    color: "text-primary",
    href: "/inicio",
  },
  {
    id: "pacientes",
    icon: "NiUsers",
    label: "menu-pacientes",
    description: "menu-pacientes-description",
    color: "text-primary",
    href: "/pacientes",
  },
  {
    id: "agenda",
    icon: "NiCalendar",
    label: "menu-agenda",
    description: "menu-agenda-description",
    color: "text-primary",
    href: "/agenda",
  },
  {
    id: "assistente",
    icon: "NiSparkle",
    label: "menu-assistente",
    description: "menu-assistente-description",
    color: "text-primary",
    href: "/applications/ai-chat",
  },
  {
    id: "admin",
    icon: "NiCrown",
    label: "menu-admin",
    description: "menu-admin-description",
    color: "text-primary",
    href: "/admin",
    superadminOnly: true,
    children: [
      {
        id: "admin-overview",
        icon: "NiDashboard",
        label: "menu-admin-overview",
        href: "/admin",
        description: "menu-admin-overview-description",
      },
      {
        id: "admin-organizations",
        icon: "NiBuilding",
        label: "menu-admin-organizations",
        href: "/admin/organizations",
        description: "menu-admin-organizations-description",
      },
      {
        id: "admin-billing",
        icon: "NiMoney",
        label: "menu-admin-billing",
        href: "/admin/billing",
        description: "menu-admin-billing-description",
      },
      {
        id: "admin-ai",
        icon: "NiAI",
        label: "menu-admin-ai",
        href: "/admin/ai",
        description: "menu-admin-ai-description",
      },
      {
        id: "admin-knowledge",
        icon: "NiBook",
        label: "menu-admin-knowledge",
        href: "/admin/knowledge",
        description: "menu-admin-knowledge-description",
      },
      {
        id: "admin-audit",
        icon: "NiShieldCheck",
        label: "menu-admin-audit",
        href: "/admin/audit",
        description: "menu-admin-audit-description",
      },
      {
        id: "admin-insights",
        icon: "NiChartLineBar",
        label: "menu-admin-insights",
        href: "/admin/insights",
        description: "menu-admin-insights-description",
      },
      {
        id: "admin-backups",
        icon: "NiArchive",
        label: "menu-admin-backups",
        href: "/admin/backups",
        description: "menu-admin-backups-description",
      },
      {
        id: "admin-announcements",
        icon: "NiAnnouncement",
        label: "menu-admin-announcements",
        href: "/admin/announcements",
        description: "menu-admin-announcements-description",
      },
      {
        id: "admin-help",
        icon: "NiQuestionHexagon",
        label: "menu-admin-help",
        href: "/admin/help",
        description: "menu-admin-help-description",
      },
      {
        id: "admin-blog",
        icon: "NiPen",
        label: "menu-admin-blog",
        href: "/admin/blog",
        description: "menu-admin-blog-description",
      },
      {
        id: "admin-support",
        icon: "NiHeadset",
        label: "menu-admin-support",
        href: "/admin/support",
        description: "menu-admin-support-description",
      },
    ],
  },
  {
    id: "ui",
    icon: "NiController",
    label: "menu-ui",
    description: "menu-ui-description",
    color: "text-primary",
    href: "/ui",
    children: [
      {
        id: "inputs",
        icon: "NiInput",
        label: "menu-inputs",
        href: "/ui/inputs",
        description: "menu-inputs-description",
        children: [
          {
            id: "autocomplete",
            label: "menu-autocomplete",
            href: "/ui/inputs/autocomplete",
            description: "menu-autocomplete-description",
            listIcon: "NiSelect",
          },
          {
            id: "button",
            label: "menu-button",
            href: "/ui/inputs/button",
            description: "menu-button-description",
            listIcon: "NiButton",
          },
          {
            id: "button-group",
            label: "menu-button-group",
            href: "/ui/inputs/button-group",
            description: "menu-button-group-description",
            listIcon: "NiButtonGroup",
          },
          {
            id: "checkbox",
            label: "menu-checkbox",
            href: "/ui/inputs/checkbox",
            description: "menu-checkbox-description",
            listIcon: "NiListCheck",
          },
          {
            id: "fab",
            label: "menu-floating-action-button",
            href: "/ui/inputs/floating-action-button",
            description: "menu-floating-action-button-description",
            listIcon: "NiButtonLarge",
          },
          {
            id: "radio-group",
            label: "menu-radio-group",
            href: "/ui/inputs/radio-group",
            description: "menu-radio-group-description",
            listIcon: "NiList",
          },
          {
            id: "rating",
            label: "menu-rating",
            href: "/ui/inputs/rating",
            description: "menu-rating-description",
            listIcon: "NiStars",
          },
          {
            id: "select",
            label: "menu-select",
            href: "/ui/inputs/select",
            description: "menu-select-description",
            listIcon: "NiSelect",
          },
          {
            id: "slider",
            label: "menu-slider",
            href: "/ui/inputs/slider",
            description: "menu-slider-description",
            listIcon: "NiSlider",
          },
          {
            id: "switch",
            label: "menu-switch",
            href: "/ui/inputs/switch",
            description: "menu-switch-description",
            listIcon: "NiSwitch",
          },
          {
            id: "text-field",
            label: "menu-text-field",
            href: "/ui/inputs/text-field",
            description: "menu-text-field-description",
            listIcon: "NiInput",
          },
          {
            id: "toggle-button",
            label: "menu-toggle-button",
            href: "/ui/inputs/toggle-button",
            description: "menu-toggle-button-description",
            listIcon: "NiCheckSquare",
          },
        ],
      },
      {
        id: "data-display",
        icon: "NiSign",
        label: "menu-data-display",
        href: "/ui/data-display",
        description: "menu-data-display-description",
        children: [
          {
            id: "avatar",
            label: "menu-avatar",
            href: "/ui/data-display/avatar",
            description: "menu-avatar-description",
            listIcon: "NiUser",
          },
          {
            id: "badge",
            label: "menu-badge",
            href: "/ui/data-display/badge",
            description: "menu-badge-description",
            listIcon: "NiBadge",
          },
          {
            id: "chip",
            label: "menu-chip",
            href: "/ui/data-display/chip",
            description: "menu-chip-description",
            listIcon: "NiButton",
          },
          {
            id: "divider",
            label: "menu-divider",
            href: "/ui/data-display/divider",
            description: "menu-divider-description",
            listIcon: "NiLayout",
          },
          {
            id: "icons",
            label: "menu-icon",
            href: "/ui/data-display/icons",
            description: "menu-icon-description",
            listIcon: "NiStar",
          },
          {
            id: "nexture-icons",
            label: "menu-nexture-icons",
            href: "/ui/data-display/nexture-icons",
            description: "menu-nexture-icons-description",
            listIcon: "NiStars",
          },
          {
            id: "list",
            label: "menu-list",
            href: "/ui/data-display/list",
            description: "menu-list-description",
            listIcon: "NiList",
          },
          {
            id: "table",
            label: "menu-table",
            href: "/ui/data-display/table",
            description: "menu-table-description",
            listIcon: "NiMasonary",
          },
          {
            id: "tooltip",
            label: "menu-tooltip",
            href: "/ui/data-display/tooltip",
            description: "menu-tooltip-description",
            listIcon: "NiMessageDots",
          },
          {
            id: "typography",
            label: "menu-typography",
            href: "/ui/data-display/typography",
            description: "menu-typography-description",
            listIcon: "NiTextBold",
          },
        ],
      },
      {
        id: "feedback",
        icon: "NiMessageFilled",
        label: "menu-feedback",
        href: "/ui/feedback",
        description: "menu-feedback-description",
        children: [
          {
            id: "alert",
            label: "menu-alert",
            href: "/ui/feedback/alert",
            description: "menu-alert-description",
            listIcon: "NiMessageCross",
          },
          {
            id: "backdrop",
            label: "menu-backdrop",
            href: "/ui/feedback/backdrop",
            description: "menu-backdrop-description",
            listIcon: "NiDuplicate",
          },
          {
            id: "dialog",
            label: "menu-dialog",
            href: "/ui/feedback/dialog",
            description: "menu-dialog-description",
            listIcon: "NiButtonLarge",
          },
          {
            id: "progress",
            label: "menu-progress",
            href: "/ui/feedback/progress",
            description: "menu-progress-description",
            listIcon: "NiProgress",
          },
          {
            id: "skeleton",
            label: "menu-skeleton",
            href: "/ui/feedback/skeleton",
            description: "menu-skeleton-description",
            listIcon: "NiRows",
          },
          {
            id: "snackbar",
            label: "menu-snackbar",
            href: "/ui/feedback/snackbar",
            description: "menu-snackbar-description",
            listIcon: "NiMessages",
          },
        ],
      },
      {
        id: "surfaces",
        icon: "NiCells",
        label: "menu-surfaces",
        href: "/ui/surfaces",
        description: "menu-surfaces-description",
        children: [
          {
            id: "accordion",
            label: "menu-accordion",
            href: "/ui/surfaces/accordion",
            description: "menu-accordion-description",
            listIcon: "NiListChevronDown",
          },
          {
            id: "card",
            label: "menu-card",
            href: "/ui/surfaces/card",
            description: "menu-card-description",
            listIcon: "NiCreditCard",
          },
          {
            id: "paper",
            label: "menu-paper",
            href: "/ui/surfaces/paper",
            description: "menu-paper-description",
            listIcon: "NiMoney",
          },
        ],
      },
      {
        id: "navigation",
        icon: "NiPath",
        label: "menu-navigation",
        href: "/ui/navigation",
        description: "menu-navigation-description",
        children: [
          {
            id: "bottom-navigation",
            label: "menu-bottom-navigation",
            href: "/ui/navigation/bottom-navigation",
            description: "menu-bottom-navigation-description",
            listIcon: "NiSigns",
          },
          {
            id: "breadcrumbs",
            label: "menu-breadcrumbs",
            href: "/ui/navigation/breadcrumbs",
            description: "menu-breadcrumbs-description",
            listIcon: "NiEllipsisHorizontal",
          },
          {
            id: "drawer",
            label: "menu-drawer",
            href: "/ui/navigation/drawer",
            description: "menu-drawer-description",
            listIcon: "NiMenuRight",
          },
          {
            id: "link",
            label: "menu-link",
            href: "/ui/navigation/link",
            description: "menu-link-description",
            listIcon: "NiLink",
          },
          {
            id: "menu",
            label: "menu-menu",
            href: "/ui/navigation/menu",
            description: "menu-menu-description",
            listIcon: "NiMenu",
          },
          {
            id: "pagination",
            label: "menu-pagination",
            href: "/ui/navigation/pagination",
            description: "menu-pagination-description",
            listIcon: "NiChevronLeftRightSmall",
          },
          {
            id: "speed-dial",
            label: "menu-speed-dial",
            href: "/ui/navigation/speed-dial",
            description: "menu-speed-dial-description",
            listIcon: "NiFlash",
          },
          {
            id: "stepper",
            label: "menu-stepper",
            href: "/ui/navigation/stepper",
            description: "menu-stepper-description",
            listIcon: "NiEndRightSmall",
          },
          {
            id: "tabs",
            label: "menu-tabs",
            href: "/ui/navigation/tabs",
            description: "menu-tabs-description",
            listIcon: "NiCols",
          },
        ],
      },
      {
        id: "layout",
        icon: "NiLayout",
        label: "menu-layout",
        href: "/ui/layout",
        description: "menu-layout-description",
        children: [
          {
            id: "box",
            label: "menu-box",
            href: "/ui/layout/box",
            description: "menu-box-description",
            listIcon: "NiSquircle",
          },
          {
            id: "grid",
            label: "menu-grid",
            href: "/ui/layout/grid",
            description: "menu-grid-description",
            listIcon: "NiLayout",
          },
          {
            id: "stack",
            label: "menu-stack",
            href: "/ui/layout/stack",
            description: "menu-stack-description",
            listIcon: "NiRows",
          },
          {
            id: "image-list",
            label: "menu-image-list",
            href: "/ui/layout/image-list",
            description: "menu-image-list-description",
            listIcon: "NiDocumentImage",
          },
        ],
      },
      {
        id: "utils",
        icon: "NiMagicWand",
        label: "menu-utils",
        href: "/ui/utils",
        description: "menu-utils-description",
        children: [
          {
            id: "click-away-listener",
            label: "menu-click-away-listener",
            href: "/ui/utils/click-away-listener",
            description: "menu-click-away-listener-description",
            listIcon: "NiCursor",
          },
          {
            id: "modal",
            label: "menu-modal",
            href: "/ui/utils/modal",
            description: "menu-modal-description",
            listIcon: "NiDuplicate",
          },
          {
            id: "popover",
            label: "menu-popover",
            href: "/ui/utils/popover",
            description: "menu-popover-description",
            listIcon: "NiMessageDots",
          },
          {
            id: "popper",
            label: "menu-popper",
            href: "/ui/utils/popper",
            description: "menu-popper-description",
            listIcon: "NiMessage",
          },
          {
            id: "portal",
            label: "menu-portal",
            href: "/ui/utils/portal",
            description: "menu-portal-description",
            listIcon: "NiArrowUp",
          },
          {
            id: "textarea-autosize",
            label: "menu-textarea-autosize",
            href: "/ui/utils/textarea-autosize",
            description: "menu-textarea-autosize-description",
            listIcon: "NiTextarea",
          },
          {
            id: "transitions",
            label: "menu-transitions",
            href: "/ui/utils/transitions",
            description: "menu-transitions-description",
            listIcon: "NiArrowLeftRight",
          },
        ],
      },
      {
        id: "mui-x",
        icon: "NiStar",
        label: "menu-mui-x",
        href: "/ui/mui-x",
        description: "menu-mui-x-description",
        children: [
          {
            id: "data-grid",
            label: "menu-data-grid",
            href: "/ui/mui-x/data-grid",
            description: "menu-data-grid-description",
            listIcon: "NiLayout",
            children: [
              {
                id: "data-grid-overview",
                label: "menu-data-grid-overview",
                description: "menu-data-grid-overview-description",
                href: "/ui/mui-x/data-grid/overview",
                listIcon: "NiLayout",
              },
              {
                id: "data-grid-full-page",
                label: "menu-data-grid-full-page",
                description: "menu-data-grid-full-page-description",
                href: "/ui/mui-x/data-grid/full-page",
                listIcon: "NiExpand",
              },

              {
                id: "data-grid-inline-editing",
                label: "menu-data-grid-inline-editing",
                description: "menu-data-grid-inline-editing-description",
                href: "/ui/mui-x/data-grid/inline-editing",
                listIcon: "NiPen",
              },
              {
                id: "data-grid-column-grouping",
                label: "menu-data-grid-column-grouping",
                description: "menu-data-grid-column-grouping-description",
                href: "/ui/mui-x/data-grid/column-grouping",
                listIcon: "NiGroup",
              },
              {
                id: "data-grid-save-and-restore-state",
                label: "menu-data-grid-save-and-restore-state",
                description: "menu-data-grid-save-and-restore-state-description",
                href: "/ui/mui-x/data-grid/save-and-restore-state",
                listIcon: "NiFloppyDisk",
              },
              {
                id: "data-grid-quick-filter",
                label: "menu-data-grid-quick-filter",
                description: "menu-data-grid-quick-filter-description",
                href: "/ui/mui-x/data-grid/quick-filter",
                listIcon: "NiFilter",
              },
              {
                id: "data-grid-column-visibility",
                label: "menu-data-grid-column-visibility",
                description: "menu-data-grid-column-visibility-description",
                href: "/ui/mui-x/data-grid/column-visibility",
                listIcon: "NiEyeOpen",
              },
              {
                id: "data-grid-column-virtualization",
                label: "menu-data-grid-column-virtualization",
                description: "menu-data-grid-column-virtualization-description",
                href: "/ui/mui-x/data-grid/column-virtualization",
                listIcon: "NiCols",
              },
              {
                id: "data-grid-master-detail",
                label: "menu-data-grid-master-detail",
                description: "menu-data-grid-master-detail-description",
                href: "/ui/mui-x/data-grid/master-detail",
                listIcon: "NiListChevronDown",
              },
              {
                id: "data-grid-lazy-loading",
                label: "menu-data-grid-lazy-loading",
                description: "menu-data-grid-lazy-loading-description",
                href: "/ui/mui-x/data-grid/lazy-loading",
                listIcon: "NiProgress",
              },
              {
                id: "data-grid-row-reordering",
                label: "menu-data-grid-row-reordering",
                description: "menu-data-grid-row-reordering-description",
                href: "/ui/mui-x/data-grid/row-reordering",
                listIcon: "NiMove",
              },
              {
                id: "data-grid-column-pinning",
                label: "menu-data-grid-column-pinning",
                description: "menu-data-grid-column-pinning-description",
                href: "/ui/mui-x/data-grid/column-pinning",
                listIcon: "NiPushPinLeft",
              },
              {
                id: "data-grid-row-pinning",
                label: "menu-data-grid-row-pinning",
                description: "menu-data-grid-row-pinning-description",
                href: "/ui/mui-x/data-grid/row-pinning",
                listIcon: "NiPushPinRight",
              },
              {
                id: "data-grid-row-virtualization",
                label: "menu-data-grid-row-virtualization",
                description: "menu-data-grid-row-virtualization-description",
                href: "/ui/mui-x/data-grid/row-virtualization",
                listIcon: "NiRows",
              },
              {
                id: "data-grid-tree-data",
                label: "menu-data-grid-tree-data",
                description: "menu-data-grid-tree-data-description",
                href: "/ui/mui-x/data-grid/tree-data",
                listIcon: "NiDirectory",
              },
              {
                id: "data-grid-header-filters",
                label: "menu-data-grid-header-filters",
                description: "menu-data-grid-header-filters-description",
                href: "/ui/mui-x/data-grid/header-filters",
                listIcon: "NiFilter",
              },
              {
                id: "data-grid-row-grouping",
                label: "menu-data-grid-row-grouping",
                description: "menu-data-grid-row-grouping-description",
                href: "/ui/mui-x/data-grid/row-grouping",
                listIcon: "NiGroup",
              },
              {
                id: "data-grid-excel-export",
                label: "menu-data-grid-excel-export",
                description: "menu-data-grid-excel-export-description",
                href: "/ui/mui-x/data-grid/excel-export",
                listIcon: "NiArrowOutUp",
              },
              {
                id: "data-grid-aggregation-and-summary-rows",
                label: "menu-data-grid-aggregation-and-summary-rows",
                description: "menu-data-grid-aggregation-and-summary-rows-description",
                href: "/ui/mui-x/data-grid/aggregation-and-summary-rows",
                listIcon: "NiSum",
              },
              {
                id: "data-grid-cell-selection",
                label: "menu-data-grid-cell-selection",
                description: "menu-data-grid-cell-selection-description",
                href: "/ui/mui-x/data-grid/cell-selection",
                listIcon: "NiBrackets",
              },
              {
                id: "data-grid-clipboard-paste",
                label: "menu-data-grid-clipboard-paste",
                description: "menu-data-grid-clipboard-paste-description",
                href: "/ui/mui-x/data-grid/clipboard-paste",
                listIcon: "NiClipboard",
              },
              {
                id: "data-grid-pivoting",
                label: "menu-data-grid-pivoting",
                description: "menu-data-grid-pivoting-description",
                href: "/ui/mui-x/data-grid/pivoting",
                listIcon: "NiPivot",
              },
              {
                id: "data-grid-ai-assistant",
                label: "menu-data-grid-ai-assistant",
                description: "menu-data-grid-ai-assistant-description",
                href: "/ui/mui-x/data-grid/ai-assistant",
                listIcon: "NiAI",
              },
            ],
          },
          {
            id: "date-time-picker",
            label: "menu-date-time-picker",
            href: "/ui/mui-x/date-time-picker",
            description: "menu-date-time-picker-description",
            listIcon: "NiCalendar",
            children: [
              {
                id: "date-time-picker-overview",
                label: "menu-date-time-picker-overview",
                href: "/ui/mui-x/date-time-picker/overview",
                description: "menu-date-time-picker-overview-description",
                listIcon: "NiCalendar",
              },
              {
                id: "date-time-picker-date",
                label: "menu-date-time-picker-date",
                href: "/ui/mui-x/date-time-picker/date",
                description: "menu-date-time-picker-date-description",
                listIcon: "NiCalendar",
              },
              {
                id: "date-time-picker-time",
                label: "menu-date-time-picker-time",
                href: "/ui/mui-x/date-time-picker/time",
                description: "menu-date-time-picker-time-description",
                listIcon: "NiClock",
              },
              {
                id: "date-time-picker-date-time",
                label: "menu-date-time-picker-date-time",
                href: "/ui/mui-x/date-time-picker/date-time",
                description: "menu-date-time-picker-date-time-description",
                listIcon: "NiCalendarClock",
              },
              {
                id: "date-time-picker-date-range",
                label: "menu-date-time-picker-date-range",
                href: "/ui/mui-x/date-time-picker/date-range",
                description: "menu-date-time-picker-date-range-description",
                listIcon: "NiCalendar",
              },
              {
                id: "date-time-picker-time-range",
                label: "menu-date-time-picker-time-range",
                href: "/ui/mui-x/date-time-picker/time-range",
                description: "menu-date-time-picker-time-range-description",
                listIcon: "NiClock",
              },
              {
                id: "date-time-picker-date-time-range",
                label: "menu-date-time-picker-date-time-range",
                href: "/ui/mui-x/date-time-picker/date-time-range",
                description: "menu-date-time-picker-date-time-range-description",
                listIcon: "NiCalendarClock",
              },
            ],
          },
          {
            id: "charts",
            label: "menu-charts",
            href: "/ui/mui-x/charts",
            description: "menu-charts-description",
            listIcon: "NiChartBar",
            children: [
              {
                id: "charts-bars",
                label: "menu-charts-bars",
                href: "/ui/mui-x/charts/bars",
                description: "menu-charts-bars",
                listIcon: "NiChartBar",
              },
              {
                id: "charts-lines",
                label: "menu-charts-lines",
                href: "/ui/mui-x/charts/lines",
                description: "menu-charts-lines",
                listIcon: "NiChartLine",
              },
              {
                id: "charts-pie",
                label: "menu-charts-pie",
                href: "/ui/mui-x/charts/pie",
                description: "menu-charts-pie",
                listIcon: "NiChartPie",
              },
              {
                id: "charts-scatter",
                label: "menu-charts-scatter",
                href: "/ui/mui-x/charts/scatter",
                description: "menu-charts-scatter",
                listIcon: "NiChartScatter",
              },
              {
                id: "charts-sparkline",
                label: "menu-charts-sparkline",
                href: "/ui/mui-x/charts/sparkline",
                description: "menu-charts-sparkline",
                listIcon: "NiTrendUp",
              },
              {
                id: "charts-gauge",
                label: "menu-charts-gauge",
                href: "/ui/mui-x/charts/gauge",
                description: "menu-charts-gauge",
                listIcon: "NiDashboard",
              },
              {
                id: "charts-radar",
                label: "menu-charts-radar",
                href: "/ui/mui-x/charts/radar",
                description: "menu-charts-radar",
                listIcon: "NiChartRadar",
              },
              {
                id: "charts-heatmap",
                label: "menu-charts-heatmap",
                href: "/ui/mui-x/charts/heatmap",
                description: "menu-charts-heatmap",
                listIcon: "NiChartHeatmap",
              },
              {
                id: "charts-funnel",
                label: "menu-charts-funnel",
                href: "/ui/mui-x/charts/funnel",
                description: "menu-charts-funnel",
                listIcon: "NiChartFunnel",
              },
            ],
          },
          {
            id: "tree-view",
            label: "menu-tree-view",
            href: "/ui/mui-x/tree-view",
            description: "menu-tree-view-description",
            listIcon: "NiDirectory",
            children: [
              {
                id: "tree-view-overview",
                label: "menu-tree-view-overview",
                href: "/ui/mui-x/tree-view/overview",
                description: "menu-tree-view-overview-description",
                listIcon: "NiDirectory",
              },
              {
                id: "tree-view-items",
                label: "menu-tree-view-items",
                href: "/ui/mui-x/tree-view/items",
                description: "menu-tree-view-items-description",
                listIcon: "NiDirectory",
              },
              {
                id: "tree-view-selection",
                label: "menu-tree-view-selection",
                href: "/ui/mui-x/tree-view/selection",
                description: "menu-tree-view-selection-description",
                listIcon: "NiDirectory",
              },
              {
                id: "tree-view-expansion",
                label: "menu-tree-view-expansion",
                href: "/ui/mui-x/tree-view/expansion",
                description: "menu-tree-view-expansion-description",
                listIcon: "NiDirectory",
              },
              {
                id: "tree-view-customization",
                label: "menu-tree-view-customization",
                href: "/ui/mui-x/tree-view/customization",
                description: "menu-tree-view-customization-description",
                listIcon: "NiDirectory",
              },
              {
                id: "tree-view-focus",
                label: "menu-tree-view-focus",
                href: "/ui/mui-x/tree-view/focus",
                description: "menu-tree-view-focus-description",
                listIcon: "NiDirectory",
              },
              {
                id: "tree-view-editing",
                label: "menu-tree-view-editing",
                href: "/ui/mui-x/tree-view/editing",
                description: "menu-tree-view-editing-description",
                listIcon: "NiDirectory",
              },
              {
                id: "tree-view-ordering",
                label: "menu-tree-view-ordering",
                href: "/ui/mui-x/tree-view/ordering",
                description: "menu-tree-view-ordering-description",
                listIcon: "NiDirectory",
              },
            ],
          },
        ],
      },
      {
        id: "lab",
        icon: "NiFlask",
        label: "menu-lab",
        href: "/ui/lab",
        description: "menu-lab",
        children: [
          {
            id: "lab-masonry",
            label: "menu-lab-masonry",
            href: "/ui/lab/masonry",
            description: "menu-lab-masonry",
            listIcon: "NiMasonary",
          },
          {
            id: "lab-timeline",
            label: "menu-lab-timeline",
            href: "/ui/lab/timeline",
            description: "menu-lab-timeline",
            listIcon: "NiTimeline",
          },
        ],
      },
      {
        id: "plugins",
        icon: "NiPuzzle",
        label: "menu-plugins",
        href: "/ui/plugins",
        description: "menu-plugins",
        children: [
          {
            id: "plugins-lightbox",
            label: "menu-plugins-lightbox",
            href: "/ui/plugins/lightbox",
            description: "menu-plugins-lightbox-description",
            listIcon: "NiDuplicate",
          },
          {
            id: "plugins-carousel",
            label: "menu-plugins-carousel",
            href: "/ui/plugins/carousel",
            description: "menu-plugins-carousel-description",
            listIcon: "NiArrowLeftRight",
          },
          {
            id: "plugins-video-player",
            label: "menu-plugins-video-player",
            href: "/ui/plugins/video-player",
            description: "menu-plugins-video-player-description",
            listIcon: "NiPlay",
          },
          {
            id: "plugins-text-editor",
            label: "menu-plugins-text-editor",
            href: "/ui/plugins/text-editor",
            description: "menu-plugins-text-editor-description",
            listIcon: "NiInput",
          },
          {
            id: "plugins-dropzone",
            label: "menu-plugins-dropzone",
            href: "/ui/plugins/dropzone",
            description: "menu-plugins-dropzone-description",
            listIcon: "NiArrowInUp",
          },
          {
            id: "plugins-validation",
            label: "menu-plugins-validation",
            href: "/ui/plugins/validation",
            description: "menu-plugins-validation-description",
            listIcon: "NiCheckSquare",
          },
        ],
      },
    ],
  },
];

export const leftMenuBottomItems: MenuItem[] = [
  {
    id: "docs",
    label: "menu-documentation",
    href: "/docs",
    icon: "NiDocumentCode",
    color: "text-primary",
  },
  { id: "settings", label: "menu-settings", href: "/settings", icon: "NiSettings" },
];
